version: '3.8'

services:
  # FastAPI Service
  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    container_name: nzubecare-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=ml_models/best_model.pkl
      - COLUMNS_PATH=ml_models/expected_columns.csv
      - ENVIRONMENT=development
    networks:
      - nzubecare-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit Service
  streamlit:
    build: 
      context: .
      dockerfile: ./streamlit_app/Dockerfile
    container_name: nzubecare-streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
      - ENVIRONMENT=development
    depends_on:
      api:
        condition: service_healthy
    networks:
      - nzubecare-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Load Balancer
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nzubecare-nginx
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
      streamlit:
        condition: service_healthy
    networks:
      - nzubecare-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  nzubecare-network:
    driver: bridge

volumes:
  model_data:
    driver: local
